default_language_version:
  python: python3.11

repos:
  # Run Ruff on all Python files. We do this before Black so that Black can
  # format the code that Ruff changes.
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.262'
    hooks:
      - id: ruff
        args: ["--fix", "--exit-non-zero-on-fix"]

  # Run Black on all Python files. This will format the code.
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
  
  # Sort Python imports using isort.
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]

  # Check if Poetry is configured correctly, and if the lock file is up to date, and if the requirements.txt file is up to date.
  - repo: https://github.com/python-poetry/poetry
    rev: '1.4.0'
    hooks:
      - id: poetry-check
      - id: poetry-lock
      - id: poetry-export
        args: ["-f", "requirements.txt", "-o", "requirements.txt", "--without-hashes"]
  
  # Run Flake8 on all Python files.
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: ["--max-line-length", "120"]

  # Run Pytest before committing.
  - repo: local
    hooks:
    -   id: tests
        name: run tests
        entry: poetry run pytest
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
