[tool.poetry]
name = "discord-twitter-webhooks"
version = "0.1.0"
description = "Stream tweets to Discord"
authors = ["Joakim Hellsén <tlovinator@gmail.com>"]
license = "GPL-3.0-or-later"
readme = "README.md"
homepage = "https://github.com/TheLovinator1/discord-twitter-webhooks"
repository = "https://github.com/TheLovinator1/discord-twitter-webhooks"
keywords = [
  "bot",
  "discord",
  "discord-twitter-webhooks",
  "tweepy",
  "discord-py-slash-command",
]

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/TheLovinator1/discord-twitter-webhooks/issues"

[tool.poetry.scripts]
bot = "discord_twitter_webhooks.main:start"

[tool.poetry.dependencies]
python = "^3.9"
dhooks = { git = "https://github.com/kyb3r/dhooks.git" }
requests = "^2.27.1"
python-dotenv = "^0.19.2"
beautifulsoup4 = "^4.10.0"
tweepy = "^4.5.0"

[tool.poetry.dev-dependencies]
pytest = "^7.0.1"
black = "^22.1.0"
mypy = "^0.931"
flake8 = "^4.0.1"
types-requests = "^2.27.10"
bandit = "^1.7.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
