[tool.poetry]
name = "discord-twitter-webhooks"
version = "2.1.0"
description = "Stream tweets to Discord"
authors = ["Joakim Hellsén <tlovinator@gmail.com>"]
license = "GPL-3.0-or-later"
readme = "README.md"
homepage = "https://github.com/TheLovinator1/discord-twitter-webhooks"
repository = "https://github.com/TheLovinator1/discord-twitter-webhooks"
keywords = ["bot", "discord", "discord-twitter-webhooks", "tweepy"]

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/TheLovinator1/discord-twitter-webhooks/issues"

[tool.poetry.scripts]
bot = "discord_twitter_webhooks.main:start"

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.28.1"
python-dotenv = "^1.0.0"
beautifulsoup4 = "^4.11.1"
tweepy = "^4.12.1"
discord-webhook = "^1.0.0"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"

[tool.black]
line-length = 120
preview = true
